# Generated by Django 3.0.7 on 2020-08-27 16:36

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import plants.helpers
import plants.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticFieldInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField()),
                ('datum_latitude', models.CharField(max_length=200)),
                ('datum_longitude', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(blank=True, null=True, storage=plants.storage_backends.PublicMediaStorage(), upload_to=plants.helpers.get_raw_upload_path)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, storage=plants.storage_backends.PublicMediaStorage(), upload_to=plants.helpers.get_profile_pic_path)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('meta_list', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('area_info_forms', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('permitted_fields', models.CharField(max_length=500, null=True)),
                ('field_id', models.CharField(choices=[('---', '---'), ('---', '---')], default='---', max_length=200, null=True)),
                ('field_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('dataset_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
