# Generated by Django 3.0.7 on 2020-08-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='field_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
