# Generated by Django 3.0.7 on 2020-08-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticfieldinfo',
            name='meters_per_pixel',
            field=models.IntegerField(default=0),
        ),
    ]
