# Generated by Django 3.0.7 on 2020-08-17 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20200816_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_collected',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
