# Generated by Django 3.0.7 on 2020-08-19 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0004_auto_20200816_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=200)),
                ('field_name', models.CharField(max_length=200)),
                ('pixels_per_meter', models.CharField(max_length=200)),
                ('rotational_offset', models.CharField(max_length=200)),
                ('datum_latitude', models.CharField(max_length=200)),
                ('datum_longitude', models.CharField(max_length=200)),
                ('camera_to_gps_x', models.CharField(max_length=200)),
                ('camera_to_gps_y', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
