# Generated by Django 3.0.7 on 2020-08-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20200818_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='permitted_fields',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='field_id',
            field=models.CharField(choices=[('he', 'he'), ('ho', 'ho')], default='---', max_length=200, null=True),
        ),
    ]
