# Generated by Django 3.0.7 on 2020-08-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20200819_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='field_id',
            field=models.CharField(choices=[('---', '---'), ('---', '---')], default='---', max_length=200, null=True),
        ),
    ]
