# Generated by Django 3.0.7 on 2020-08-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20200819_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldinfo',
            old_name='camera_to_gps_x',
            new_name='camera_to_gps_x_meters',
        ),
        migrations.RenameField(
            model_name='fieldinfo',
            old_name='camera_to_gps_y',
            new_name='camera_to_gps_y_meters',
        ),
        migrations.RenameField(
            model_name='fieldinfo',
            old_name='rotational_offset',
            new_name='rotational_offset_degrees',
        ),
    ]
