# Generated by Django 3.0.7 on 2020-08-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20200819_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldinfo',
            old_name='camera_to_gps_x_meters',
            new_name='field_id',
        ),
        migrations.RemoveField(
            model_name='fieldinfo',
            name='camera_to_gps_y_meters',
        ),
        migrations.RemoveField(
            model_name='fieldinfo',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='fieldinfo',
            name='operator_name',
        ),
        migrations.RemoveField(
            model_name='fieldinfo',
            name='pixels_per_meter',
        ),
        migrations.RemoveField(
            model_name='fieldinfo',
            name='rotational_offset_degrees',
        ),
    ]
