# Generated by Django 3.0.7 on 2020-06-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20200614_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.FileField(upload_to='images')),
            ],
        ),
    ]
