# Generated by Django 3.0.7 on 2020-08-20 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0010_auto_20200820_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=200)),
                ('camera_height', models.CharField(max_length=200)),
                ('rotational_offset', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='FieldInfo',
            new_name='StaticFieldInfo',
        ),
    ]
