# Generated by Django 3.0.7 on 2020-06-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_fileupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='Document',
        ),
    ]
