# Generated by Django 3.0.7 on 2020-08-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_auto_20200820_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectioninfo',
            old_name='camera_height',
            new_name='camera_height_meters',
        ),
        migrations.RenameField(
            model_name='collectioninfo',
            old_name='rotational_offset',
            new_name='rotational_offset_degrees',
        ),
    ]
