# Generated by Django 3.0.7 on 2020-08-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_auto_20200820_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionInfo',
        ),
        migrations.AlterField(
            model_name='staticfieldinfo',
            name='field_id',
            field=models.IntegerField(max_length=200),
        ),
    ]
