# Generated by Django 3.0.7 on 2020-06-19 18:22

from django.db import migrations, models
import plants.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_auto_20200618_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=plants.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(storage=plants.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
