# Generated by Django 3.0.7 on 2020-06-20 22:56

from django.db import migrations, models
import plants.helpers
import plants.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_auto_20200619_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_file_upload',
            field=models.FileField(blank=True, null=True, storage=plants.storage_backends.PrivateMediaStorage(), upload_to=plants.helpers.get_csv_path),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pic.jpg', null=True, storage=plants.storage_backends.PrivateMediaStorage(), upload_to=plants.helpers.get_profile_pic_path),
        ),
    ]
