# Generated by Django 3.0.7 on 2020-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_auto_20200821_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfieldinfo',
            name='field_id',
            field=models.IntegerField(),
        ),
    ]
