# Generated by Django 3.0.7 on 2020-06-20 23:01

from django.db import migrations, models
import plants.helpers
import plants.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_auto_20200620_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pic.jpg', null=True, storage=plants.storage_backends.PublicMediaStorage(), upload_to=plants.helpers.get_profile_pic_path),
        ),
    ]
