# Generated by Django 3.0.7 on 2020-06-21 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_auto_20200620_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.DeleteModel(
            name='UploadPrivate',
        ),
    ]
