# Generated by Django 3.0.7 on 2020-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0017_auto_20200621_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='meta_list',
            field=models.TextField(null=True),
        ),
    ]
