# Generated by Django 3.0.7 on 2020-07-13 03:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0018_customer_meta_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='meta_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
