# Generated by Django 3.0.7 on 2020-07-13 04:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0019_auto_20200712_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='meta_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
