# Generated by Django 3.0.7 on 2020-07-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0020_auto_20200713_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='should_ignore_warnings',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
