# Generated by Django 3.0.7 on 2020-07-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0021_customer_should_ignore_warnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='should_ignore_warnings',
        ),
    ]
