# Generated by Django 3.0.7 on 2020-07-29 22:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0022_remove_customer_should_ignore_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorite_plants_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
