# Generated by Django 3.0.7 on 2020-08-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0023_customer_favorite_plants_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorite_plants_info',
        ),
    ]
