# Generated by Django 3.0.7 on 2020-08-06 20:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0024_remove_customer_favorite_plants_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_shapes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
